### ISSUE TITLE
Failed to build x86_64-pc-windows-msvc on linux

### ISSUE THREAD

**Issue by DBLouis** [alexcrichton/curl-rust#511]
I am trying to build on Ubuntu (22.04.2 LTS) with the `x86_64-pc-windows-msvc` toolchain.

I setup the toolchain using [this guide](https://bevy-cheatbook.github.io/setup/cross/linux-windows.html).

I use this cargo config: 

```
[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
linker = "lld-link-15"
rustflags = [
  "-Lnative=/home/louis/.xwin/crt/lib/x86_64",
  "-Lnative=/home/louis/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/louis/.xwin/sdk/lib/ucrt/x86_64"
]

[env]
CC_x86_64_pc_windows_msvc = "clang-cl-15"
CXX_x86_64_pc_windows_msvc = "clang-cl-15"
CFLAGS_x86_64_pc_windows_msvc = "-Wno-everything -flto=thin -fuse-ld=lld-link -I/home/louis/.xwin/crt/include -I/home/louis/.xwin/sdk/include/um -I/home/louis/.xwin/sdk/include/ucrt -I/home/louis/.xwin/sdk/include/shared"
CXXFLAGS_x86_64_pc_windows_msvc = "-Wno-everything -flto=thin -fuse-ld=lld-link -I/home/louis/.xwin/crt/include -I/home/louis/.xwin/sdk/include/um -I/home/louis/.xwin/sdk/include/ucrt -I/home/louis/.xwin/sdk/include/shared"
AR_x86_64_pc_windows_msvc = "llvm-lib-15"
```

Output logs:

```
   Compiling curl-sys v0.4.63+curl-8.1.2 (/home/louis/Projects/curl-rust/curl-sys)
The following warnings were emitted during compilation:

warning: curl/lib/vtls/vtls.c(383,6): error: incomplete definition of type 'struct Curl_share'
warning:   if(SSLSESSION_SHARED(data))
warning:      ^~~~~~~~~~~~~~~~~~~~~~~
warning: curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
warning:                                  (data->share->specifier &             \
warning:                                   ~~~~~~~~~~~^
warning: curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
warning: typedef struct Curl_share CURLSH;
warning:                ^
warning: curl/lib/vtls/vtls.c(392,6): error: incomplete definition of type 'struct Curl_share'
warning:   if(SSLSESSION_SHARED(data))
warning:      ^~~~~~~~~~~~~~~~~~~~~~~
warning: curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
warning:                                  (data->share->specifier &             \
warning:                                   ~~~~~~~~~~~^
warning: curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
warning: typedef struct Curl_share CURLSH;
warning:                ^
warning: curl/lib/vtls/vtls.c(425,6): error: incomplete definition of type 'struct Curl_share'
warning:   if(SSLSESSION_SHARED(data))
warning:      ^~~~~~~~~~~~~~~~~~~~~~~
warning: curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
warning:                                  (data->share->specifier &             \
warning:                                   ~~~~~~~~~~~^
warning: curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
warning: typedef struct Curl_share CURLSH;
warning:                ^
warning: curl/lib/vtls/vtls.c(426,31): error: incomplete definition of type 'struct Curl_share'
warning:     general_age = &data->share->sessionage;
warning:                    ~~~~~~~~~~~^
warning: curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
warning: typedef struct Curl_share CURLSH;
warning:                ^
warning: curl/lib/vtls/vtls.c(558,6): error: incomplete definition of type 'struct Curl_share'
warning:   if(SSLSESSION_SHARED(data)) {
warning:      ^~~~~~~~~~~~~~~~~~~~~~~
warning: curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
warning:                                  (data->share->specifier &             \
warning:                                   ~~~~~~~~~~~^
warning: curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
warning: typedef struct Curl_share CURLSH;
warning:                ^
warning: curl/lib/vtls/vtls.c(559,31): error: incomplete definition of type 'struct Curl_share'
warning:     general_age = &data->share->sessionage;
warning:                    ~~~~~~~~~~~^
warning: curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
warning: typedef struct Curl_share CURLSH;
warning:                ^
warning: curl/lib/vtls/vtls.c(619,30): error: incomplete definition of type 'struct Curl_share'
warning:   if(data->state.session && !SSLSESSION_SHARED(data)) {
warning:                              ^~~~~~~~~~~~~~~~~~~~~~~
warning: curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
warning:                                  (data->share->specifier &             \
warning:                                   ~~~~~~~~~~~^
warning: curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
warning: typedef struct Curl_share CURLSH;
warning:                ^
warning: 7 errors generated.

error: failed to run custom build command for `curl-sys v0.4.63+curl-8.1.2 (/home/louis/Projects/curl-rust/curl-sys)`

Caused by:
  process didn't exit successfully: `/home/louis/Projects/curl-rust/target/debug/build/curl-sys-a9347fc56978c32c/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=curl
  cargo:root=/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/curl-sys-6cb84f36098fe8a1/out
  cargo:include=/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/curl-sys-6cb84f36098fe8a1/out/include
  cargo:static=1
  cargo:rustc-cfg=libcurl_vendored
  cargo:rustc-cfg=link_libz
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = Some("clang-cl-15")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = Some("-Wno-everything -flto=thin -fuse-ld=lld-link -I/home/louis/.xwin/crt/include -I/home/louis/.xwin/sdk/include/um -I/home/louis/.xwin/sdk/include/ucrt -I/home/louis/.xwin/sdk/include/shared")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  running: "clang-cl-15" "-nologo" "-MD" "-Z7" "-Brepro" "-m64" "-Wno-everything" "-flto=thin" "-fuse-ld=lld-link" "-I/home/louis/.xwin/crt/include" "-I/home/louis/.xwin/sdk/include/um" "-I/home/louis/.xwin/sdk/include/ucrt" "-I/home/louis/.xwin/sdk/include/shared" "-I" "curl/lib" "-I" "curl/include" "-I" "/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/libz-sys-2f4a9f07663a1ba8/out/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LONGLONG" "-DHAVE_LIBZ" "-DHAVE_BOOL_T" "-DHAVE_STDBOOL_H" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_FTP" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-Fo/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/curl-sys-6cb84f36098fe8a1/out/build/curl/lib/asyn-thread.o" "-c" "--" "curl/lib/asyn-thread.c"
  exit status: 0
[...]
  exit status: 0
  running: "clang-cl-15" "-nologo" "-MD" "-Z7" "-Brepro" "-m64" "-Wno-everything" "-flto=thin" "-fuse-ld=lld-link" "-I/home/louis/.xwin/crt/include" "-I/home/louis/.xwin/sdk/include/um" "-I/home/louis/.xwin/sdk/include/ucrt" "-I/home/louis/.xwin/sdk/include/shared" "-I" "curl/lib" "-I" "curl/include" "-I" "/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/libz-sys-2f4a9f07663a1ba8/out/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LONGLONG" "-DHAVE_LIBZ" "-DHAVE_BOOL_T" "-DHAVE_STDBOOL_H" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_FTP" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-Fo/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/curl-sys-6cb84f36098fe8a1/out/build/curl/lib/vtls/keylog.o" "-c" "--" "curl/lib/vtls/keylog.c"
  exit status: 0
  running: "clang-cl-15" "-nologo" "-MD" "-Z7" "-Brepro" "-m64" "-Wno-everything" "-flto=thin" "-fuse-ld=lld-link" "-I/home/louis/.xwin/crt/include" "-I/home/louis/.xwin/sdk/include/um" "-I/home/louis/.xwin/sdk/include/ucrt" "-I/home/louis/.xwin/sdk/include/shared" "-I" "curl/lib" "-I" "curl/include" "-I" "/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/libz-sys-2f4a9f07663a1ba8/out/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LONGLONG" "-DHAVE_LIBZ" "-DHAVE_BOOL_T" "-DHAVE_STDBOOL_H" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_FTP" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-Fo/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/curl-sys-6cb84f36098fe8a1/out/build/curl/lib/vtls/vtls.o" "-c" "--" "curl/lib/vtls/vtls.c"
  cargo:warning=curl/lib/vtls/vtls.c(383,6): error: incomplete definition of type 'struct Curl_share'
  cargo:warning=  if(SSLSESSION_SHARED(data))
  cargo:warning=     ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
  cargo:warning=                                 (data->share->specifier &             \
  cargo:warning=                                  ~~~~~~~~~~~^
  cargo:warning=curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
  cargo:warning=typedef struct Curl_share CURLSH;
  cargo:warning=               ^
  cargo:warning=curl/lib/vtls/vtls.c(392,6): error: incomplete definition of type 'struct Curl_share'
  cargo:warning=  if(SSLSESSION_SHARED(data))
  cargo:warning=     ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
  cargo:warning=                                 (data->share->specifier &             \
  cargo:warning=                                  ~~~~~~~~~~~^
  cargo:warning=curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
  cargo:warning=typedef struct Curl_share CURLSH;
  cargo:warning=               ^
  cargo:warning=curl/lib/vtls/vtls.c(425,6): error: incomplete definition of type 'struct Curl_share'
  cargo:warning=  if(SSLSESSION_SHARED(data))
  cargo:warning=     ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
  cargo:warning=                                 (data->share->specifier &             \
  cargo:warning=                                  ~~~~~~~~~~~^
  cargo:warning=curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
  cargo:warning=typedef struct Curl_share CURLSH;
  cargo:warning=               ^
  cargo:warning=curl/lib/vtls/vtls.c(426,31): error: incomplete definition of type 'struct Curl_share'
  cargo:warning=    general_age = &data->share->sessionage;
  cargo:warning=                   ~~~~~~~~~~~^
  cargo:warning=curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
  cargo:warning=typedef struct Curl_share CURLSH;
  cargo:warning=               ^
  cargo:warning=curl/lib/vtls/vtls.c(558,6): error: incomplete definition of type 'struct Curl_share'
  cargo:warning=  if(SSLSESSION_SHARED(data)) {
  cargo:warning=     ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
  cargo:warning=                                 (data->share->specifier &             \
  cargo:warning=                                  ~~~~~~~~~~~^
  cargo:warning=curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
  cargo:warning=typedef struct Curl_share CURLSH;
  cargo:warning=               ^
  cargo:warning=curl/lib/vtls/vtls.c(559,31): error: incomplete definition of type 'struct Curl_share'
  cargo:warning=    general_age = &data->share->sessionage;
  cargo:warning=                   ~~~~~~~~~~~^
  cargo:warning=curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
  cargo:warning=typedef struct Curl_share CURLSH;
  cargo:warning=               ^
  cargo:warning=curl/lib/vtls/vtls.c(619,30): error: incomplete definition of type 'struct Curl_share'
  cargo:warning=  if(data->state.session && !SSLSESSION_SHARED(data)) {
  cargo:warning=                             ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=curl/lib/vtls/vtls.c(79,46): note: expanded from macro 'SSLSESSION_SHARED'
  cargo:warning=                                 (data->share->specifier &             \
  cargo:warning=                                  ~~~~~~~~~~~^
  cargo:warning=curl/include/curl/curl.h(119,16): note: forward declaration of 'struct Curl_share'
  cargo:warning=typedef struct Curl_share CURLSH;
  cargo:warning=               ^
  cargo:warning=7 errors generated.
  exit status: 1

  --- stderr


  error occurred: Command "clang-cl-15" "-nologo" "-MD" "-Z7" "-Brepro" "-m64" "-Wno-everything" "-flto=thin" "-fuse-ld=lld-link" "-I/home/louis/.xwin/crt/include" "-I/home/louis/.xwin/sdk/include/um" "-I/home/louis/.xwin/sdk/include/ucrt" "-I/home/louis/.xwin/sdk/include/shared" "-I" "curl/lib" "-I" "curl/include" "-I" "/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/libz-sys-2f4a9f07663a1ba8/out/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LONGLONG" "-DHAVE_LIBZ" "-DHAVE_BOOL_T" "-DHAVE_STDBOOL_H" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_FTP" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-Fo/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/curl-sys-6cb84f36098fe8a1/out/build/curl/lib/vtls/vtls.o" "-c" "--" "curl/lib/vtls/vtls.c" with args "clang-cl-15" did not execute successfully (status code exit status: 1).

```

**Comment by DBLouis** [comment]
I also tried with `--features windows-static-ssl` and get a different error:

```
  running: "clang-cl-15" "-nologo" "-MD" "-Z7" "-Brepro" "-m64" "-Wno-everything" "-flto=thin" "-fuse-ld=lld-link" "-I/home/louis/.xwin/crt/include" "-I/home/louis/.xwin/sdk/include/um" "-I/home/louis/.xwin/sdk/include/ucrt" "-I/home/louis/.xwin/sdk/include/shared" "-I" "curl/lib" "-I" "curl/include" "-I" "/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/libz-sys-2f4a9f07663a1ba8/out/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LONGLONG" "-DHAVE_LIBZ" "-DHAVE_BOOL_T" "-DHAVE_STDBOOL_H" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_FTP" "-DUSE_OPENSSL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-Fo/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/curl-sys-ce50ce89b7dde1e9/out/build/curl/lib/md5.o" "-c" "--" "curl/lib/md5.c"
  cargo:warning=curl/lib/md5.c(46,12): fatal error: 'openssl/opensslconf.h' file not found
  cargo:warning=  #include <openssl/opensslconf.h>
  cargo:warning=           ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr


  error occurred: Command "clang-cl-15" "-nologo" "-MD" "-Z7" "-Brepro" "-m64" "-Wno-everything" "-flto=thin" "-fuse-ld=lld-link" "-I/home/louis/.xwin/crt/include" "-I/home/louis/.xwin/sdk/include/um" "-I/home/louis/.xwin/sdk/include/ucrt" "-I/home/louis/.xwin/sdk/include/shared" "-I" "curl/lib" "-I" "curl/include" "-I" "/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/libz-sys-2f4a9f07663a1ba8/out/include" "-DBUILDING_LIBCURL" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LONGLONG" "-DHAVE_LIBZ" "-DHAVE_BOOL_T" "-DHAVE_STDBOOL_H" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_NTLM" "-DCURL_DISABLE_FTP" "-DUSE_OPENSSL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-Fo/home/louis/Projects/curl-rust/target/x86_64-pc-windows-msvc/debug/build/curl-sys-ce50ce89b7dde1e9/out/build/curl/lib/md5.o" "-c" "--" "curl/lib/md5.c" with args "clang-cl-15" did not execute successfully (status code exit status: 1).
```

**Comment by DBLouis** [comment]
I fixed my issue by using cargo-xwin.
