### ISSUE TITLE
curl-sys fails to compile with LibreSSL 2.7.3

### ISSUE THREAD

**Issue by vpzomtrrfrt** [alexcrichton/curl-rust#210]
Attempting to compile curl-sys on my system results in the following error:

```
configure: WARNING: OpenSSL headers and library versions do not match.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^((\w).*){ <-- HERE \z/ at /home/colin/curl-rust/curl-sys/curl/lib/checksrc.pl line 516.
/home/colin/curl-rust/curl-sys/curl/lib/vtls/openssl.c:124:22: error: static declaration of 'OpenSSL_version_num' follows non-static declaration
 static unsigned long OpenSSL_version_num(void)
                      ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/bio.h:69:0,
                 from /usr/include/openssl/evp.h:67,
                 from /usr/include/openssl/hmac.h:67,
                 from /usr/include/openssl/ssl.h:149,
                 from /home/colin/curl-rust/curl-sys/curl/lib/urldata.h:86,
                 from /home/colin/curl-rust/curl-sys/curl/lib/vtls/openssl.c:41:
/usr/include/openssl/crypto.h:340:15: note: previous declaration of 'OpenSSL_version_num' was here
 unsigned long OpenSSL_version_num(void);
               ^~~~~~~~~~~~~~~~~~~
/home/colin/curl-rust/curl-sys/curl/lib/vtls/openssl.c:124:22: error: static declaration of 'OpenSSL_version_num' follows non-static declaration
 static unsigned long OpenSSL_version_num(void)
                      ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/bio.h:69:0,
                 from /usr/include/openssl/evp.h:67,
                 from /usr/include/openssl/hmac.h:67,
                 from /usr/include/openssl/ssl.h:149,
                 from /home/colin/curl-rust/curl-sys/curl/lib/urldata.h:86,
                 from /home/colin/curl-rust/curl-sys/curl/lib/vtls/openssl.c:41:
/usr/include/openssl/crypto.h:340:15: note: previous declaration of 'OpenSSL_version_num' was here
 unsigned long OpenSSL_version_num(void);
               ^~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:2898: vtls/libcurlu_la-openssl.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:2023: vtls/libcurl_la-openssl.lo] Error 1
make[1]: *** [Makefile:734: all] Error 2
make: *** [Makefile:897: all-recursive] Error 1
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', curl-sys/build.rs:224:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by alexcrichton** [comment]
I've opened a PR for this at https://github.com/alexcrichton/curl-rust/pull/214, will merge once CI is green

**Comment by WnP** [comment]
Installing `libcurl-devel` fix this issue

**Comment by WnP** [comment]
`curl-sys` still doesn't compile on void linux (which use `libressl`) without `libcurl-devel` even with `curl-sys==0.4.8` (latest).

Here is a simpler test case:

directory structure:
```
.
├── Dockerfile
└── test_curl_sys
    ├── Cargo.toml
    └── src
        └── main.rs
```

- `Dockerfile`:
```dockerfile
FROM voidlinux/voidlinux

COPY test_curl_sys /test_curl_sys
RUN xbps-install -Sy \
    rust cargo libressl-devel \
    cmake make gcc pkg-config \
    && cd test_curl_sys \
    && cargo run
```
- `Cargo.toml`:
```toml
[package]
name = "test_curl_sys"
version = "0.1.0"
authors = ["me <me@here.io>"]

[dependencies]
curl-sys = "0.4.8"
```
- `main.rs`:
```rust
fn main() {
    println!("Hello curl-sys");
}
```

By the way installing `libcurl-devel` still fix this issue.

I just put this here as a reminder.
