### ISSUE TITLE
failed to link in Ubuntu 20.04

### ISSUE THREAD

**Issue by keepsimple1** [alexcrichton/curl-rust#439]
I'm using `curl 0.4.42`. My program built OK on macOS, but failed to build on  Ubuntu 20.04 due many linker errors: 

Two examples are:
```
          /usr/include/openssl/x509.h:85: undefined reference to `OPENSSL_sk_num'
          /usr/include/openssl/x509.h:85: undefined reference to `OPENSSL_sk_value'
```

I installed `libc6-dev`, `libssl-dev` and `libcurl4-openssl-dev`, but did not resolve the errors.  What are I missing to fix these linker errors?  Thanks.

**Comment by Boiethios** [comment]
I get the same kind of error on Fedora, even though I installed `openssl-devel` and `libcurl-devel`. Did you solve your issue?

```
undefined reference to `EVP_PKEY_id'
undefined reference to `SSL_get_peer_certificate'
undefined reference to `EVP_PKEY_id'
undefined reference to `SSL_get_peer_certificate'
```
